services:
  - type: web
    name: selenium-flask-app
    runtime: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
